version: '2'
services:
  flask:
    build: ./flask
    ports:
     - "5000:5000"
    volumes:
     - .:/work
    tty: true
    depends_on:
     - redis
    links:
     - redis
  redis:
    build: ./redis
    ports:
     - "6379:6379"
    tty: true
